const types = {
  GET_DRINK_CATEGORIES: 'GET_DRINK_CATEGORIES',
  GET_DRINKS: 'GET_DRINKS',
  APPLY_CATEGORY_FILTERS: 'APPLY_CATEGORY_FILTERS',
  SET_LIST_COMPLETED: 'SET_LIST_COMPLETED',
};

export default types;
